export const clientEnv = {
  DEV: process.env.NODE_ENV !== 'production',
  PROD: process.env.NODE_ENV === 'production',
  BASE_URL: '/',
  VITE_DEFAULT_API_URL: process.env.NEXT_PUBLIC_DEFAULT_API_URL,
  VITE_DEFAULT_PROVIDER: process.env.NEXT_PUBLIC_DEFAULT_PROVIDER,
  VITE_API_PROXY_AVAILABLE: process.env.NEXT_PUBLIC_API_PROXY_AVAILABLE,
  VITE_API_PROXY_LOCKED: process.env.NEXT_PUBLIC_API_PROXY_LOCKED,
  VITE_DOCKER_DEPLOYMENT: process.env.NEXT_PUBLIC_DOCKER_DEPLOYMENT,
  VITE_DOCKER_LEGACY_API_URL_USED: process.env.NEXT_PUBLIC_DOCKER_LEGACY_API_URL_USED,
  VITE_ENABLE_VERSION_CHECK: process.env.NEXT_PUBLIC_ENABLE_VERSION_CHECK,
}
